// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-pr-review-agent/pkg"
)

type PRStateClient struct {
	PRDiffStub        func(context.Context, string) (string, error)
	pRDiffMutex       sync.RWMutex
	pRDiffArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	pRDiffReturns struct {
		result1 string
		result2 error
	}
	pRDiffReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	PRStateStub        func(context.Context, string) (string, string, string, error)
	pRStateMutex       sync.RWMutex
	pRStateArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	pRStateReturns struct {
		result1 string
		result2 string
		result3 string
		result4 error
	}
	pRStateReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 string
		result4 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PRStateClient) PRDiff(arg1 context.Context, arg2 string) (string, error) {
	fake.pRDiffMutex.Lock()
	ret, specificReturn := fake.pRDiffReturnsOnCall[len(fake.pRDiffArgsForCall)]
	fake.pRDiffArgsForCall = append(fake.pRDiffArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PRDiffStub
	fakeReturns := fake.pRDiffReturns
	fake.recordInvocation("PRDiff", []interface{}{arg1, arg2})
	fake.pRDiffMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PRStateClient) PRDiffCallCount() int {
	fake.pRDiffMutex.RLock()
	defer fake.pRDiffMutex.RUnlock()
	return len(fake.pRDiffArgsForCall)
}

func (fake *PRStateClient) PRDiffCalls(stub func(context.Context, string) (string, error)) {
	fake.pRDiffMutex.Lock()
	defer fake.pRDiffMutex.Unlock()
	fake.PRDiffStub = stub
}

func (fake *PRStateClient) PRDiffArgsForCall(i int) (context.Context, string) {
	fake.pRDiffMutex.RLock()
	defer fake.pRDiffMutex.RUnlock()
	argsForCall := fake.pRDiffArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PRStateClient) PRDiffReturns(result1 string, result2 error) {
	fake.pRDiffMutex.Lock()
	defer fake.pRDiffMutex.Unlock()
	fake.PRDiffStub = nil
	fake.pRDiffReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PRStateClient) PRDiffReturnsOnCall(i int, result1 string, result2 error) {
	fake.pRDiffMutex.Lock()
	defer fake.pRDiffMutex.Unlock()
	fake.PRDiffStub = nil
	if fake.pRDiffReturnsOnCall == nil {
		fake.pRDiffReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.pRDiffReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PRStateClient) PRState(arg1 context.Context, arg2 string) (string, string, string, error) {
	fake.pRStateMutex.Lock()
	ret, specificReturn := fake.pRStateReturnsOnCall[len(fake.pRStateArgsForCall)]
	fake.pRStateArgsForCall = append(fake.pRStateArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PRStateStub
	fakeReturns := fake.pRStateReturns
	fake.recordInvocation("PRState", []interface{}{arg1, arg2})
	fake.pRStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4
}

func (fake *PRStateClient) PRStateCallCount() int {
	fake.pRStateMutex.RLock()
	defer fake.pRStateMutex.RUnlock()
	return len(fake.pRStateArgsForCall)
}

func (fake *PRStateClient) PRStateCalls(stub func(context.Context, string) (string, string, string, error)) {
	fake.pRStateMutex.Lock()
	defer fake.pRStateMutex.Unlock()
	fake.PRStateStub = stub
}

func (fake *PRStateClient) PRStateArgsForCall(i int) (context.Context, string) {
	fake.pRStateMutex.RLock()
	defer fake.pRStateMutex.RUnlock()
	argsForCall := fake.pRStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PRStateClient) PRStateReturns(result1 string, result2 string, result3 string, result4 error) {
	fake.pRStateMutex.Lock()
	defer fake.pRStateMutex.Unlock()
	fake.PRStateStub = nil
	fake.pRStateReturns = struct {
		result1 string
		result2 string
		result3 string
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *PRStateClient) PRStateReturnsOnCall(i int, result1 string, result2 string, result3 string, result4 error) {
	fake.pRStateMutex.Lock()
	defer fake.pRStateMutex.Unlock()
	fake.PRStateStub = nil
	if fake.pRStateReturnsOnCall == nil {
		fake.pRStateReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 string
			result4 error
		})
	}
	fake.pRStateReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 string
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *PRStateClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PRStateClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.PRStateClient = new(PRStateClient)
